services:
  mongodb:
    image: mongo
    container_name: mongodb-Messungen
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./db:/data/db
